import { DashboardSummary } from '../models/checklist.model';

export const MOCK_DASHBOARD: DashboardSummary = {
  totalActive: 6,
  completedToday: 2,
  overdue: 1,
  avgCompletionRate: 74,
  checklists: [
    {
      id: '1',
      name: 'Daily Opening Checklist',
      description: 'Tasks to complete before opening the facility',
      status: 'active',
      recurrence: 'daily',
      completionRate: 100,
      totalTasks: 8,
      completedTasks: 8,
      overdueTasks: 0,
      assignedTeam: 'Operations',
      dueDate: new Date().toISOString(),
      createdAt: '2026-04-01T00:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: '2',
      name: 'Weekly Safety Inspection',
      description: 'Mandatory safety walk-through and equipment checks',
      status: 'active',
      recurrence: 'weekly',
      completionRate: 60,
      totalTasks: 15,
      completedTasks: 9,
      overdueTasks: 0,
      assignedTeam: 'Safety',
      dueDate: new Date(Date.now() + 86400000 * 2).toISOString(),
      createdAt: '2026-04-01T00:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: '3',
      name: 'Monthly Compliance Review',
      description: 'HIPAA compliance documentation and audit trail review',
      status: 'overdue',
      recurrence: 'monthly',
      completionRate: 33,
      totalTasks: 12,
      completedTasks: 4,
      overdueTasks: 3,
      assignedTeam: 'Compliance',
      dueDate: new Date(Date.now() - 86400000).toISOString(),
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: '4',
      name: 'Equipment Maintenance Log',
      description: 'Monthly equipment checks and maintenance records',
      status: 'active',
      recurrence: 'monthly',
      completionRate: 80,
      totalTasks: 10,
      completedTasks: 8,
      overdueTasks: 0,
      assignedTeam: 'Facilities',
      dueDate: new Date(Date.now() + 86400000 * 5).toISOString(),
      createdAt: '2026-04-01T00:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: '5',
      name: 'Daily Closing Checklist',
      description: 'End-of-day shutdown and security procedures',
      status: 'completed',
      recurrence: 'daily',
      completionRate: 100,
      totalTasks: 6,
      completedTasks: 6,
      overdueTasks: 0,
      assignedTeam: 'Operations',
      dueDate: new Date().toISOString(),
      createdAt: '2026-04-01T00:00:00Z',
      updatedAt: new Date().toISOString(),
    },
    {
      id: '6',
      name: 'Annual Policy Review',
      description: 'Yearly review and sign-off of all team policies',
      status: 'active',
      recurrence: 'yearly',
      completionRate: 25,
      totalTasks: 20,
      completedTasks: 5,
      overdueTasks: 0,
      assignedTeam: 'HR',
      dueDate: new Date(Date.now() + 86400000 * 30).toISOString(),
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: new Date().toISOString(),
    },
  ],
};
